"""initial schema: users, broker_credentials, user_settings, trades, events, notifications

Revision ID: 0001
Revises:
Create Date: 2026-07-18

NOTE: hand-written, not autogenerated -- this sandbox has no network
access, so I could not run `alembic revision --autogenerate` against a
real Postgres instance. Please review this against your models (or just
run autogenerate yourself and diff it against this) before trusting it,
per this project's own "test every change in isolation" standard.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "broker_credentials",
        sa.Column("credential_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.user_id"), nullable=False),
        sa.Column("broker_name", sa.String(), nullable=False),
        sa.Column("account_login_enc", sa.String(), nullable=False),
        sa.Column("account_password_enc", sa.String(), nullable=False),
        sa.Column("server", sa.String(), nullable=False),
        sa.Column("account_type", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.create_index("ix_broker_credentials_user_id", "broker_credentials", ["user_id"])

    op.create_table(
        "user_settings",
        sa.Column("setting_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.user_id"),
            nullable=False,
        ),
        sa.Column("instrument", sa.String(), nullable=False, server_default="EURUSD"),
        sa.Column("live_model", sa.String(), nullable=False),
        sa.Column(
            "shadow_models",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("risk_pct", sa.Float(), nullable=False),
        sa.Column("max_daily_loss_pct", sa.Float(), nullable=False),
        sa.Column("max_concurrent_positions", sa.Integer(), nullable=False, server_default="1"),
        sa.Column(
            "news_filters",
            postgresql.JSONB(),
            nullable=False,
            server_default='{"FOMC": true, "NFP": false, "ECB": false, "CPI": false}',
        ),
        sa.Column("demo_or_live", sa.String(), nullable=False, server_default="demo"),
        sa.Column("is_paused", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.CheckConstraint("live_model IN ('fvg', 'ob', 'fvg_ob')", name="ck_user_settings_live_model_valid"),
        sa.CheckConstraint("demo_or_live IN ('demo', 'live')", name="ck_user_settings_demo_or_live_valid"),
        sa.CheckConstraint(
            "NOT (live_model = ANY(shadow_models))", name="ck_user_settings_live_not_in_shadow"
        ),
    )
    op.create_index("ix_user_settings_user_id", "user_settings", ["user_id"], unique=True)

    op.create_table(
        "trades",
        sa.Column("trade_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.user_id"), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("is_shadow", sa.Boolean(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("stop_price", sa.Float(), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=False),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("realized_r", sa.Float(), nullable=True),
        sa.Column("entry_time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entry_time_ny", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exit_time_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_pct_used", sa.Float(), nullable=False),
        sa.Column("equity_before", sa.Float(), nullable=False),
        sa.Column("equity_after", sa.Float(), nullable=True),
        sa.Column("setup_context", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.CheckConstraint("model IN ('fvg', 'ob', 'fvg_ob')", name="ck_trades_model_valid"),
        sa.CheckConstraint("direction IN ('long', 'short')", name="ck_trades_direction_valid"),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN ('win', 'loss', 'scratch')", name="ck_trades_outcome_valid"
        ),
    )
    op.create_index("ix_trades_user_id", "trades", ["user_id"])

    op.create_table(
        "events",
        sa.Column("event_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.user_id"), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("details", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.CheckConstraint("model IN ('fvg', 'ob', 'fvg_ob')", name="ck_events_model_valid"),
    )
    op.create_index("ix_events_user_id", "events", ["user_id"])
    op.create_index("ix_events_event_type", "events", ["event_type"])

    op.create_table(
        "notifications",
        sa.Column("notification_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.user_id"), nullable=False),
        sa.Column("channel_type", sa.String(), nullable=False, server_default="email"),
        sa.Column("destination", sa.String(), nullable=False),
        sa.Column("event_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("events.event_id"), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="pending"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"])


def downgrade() -> None:
    op.drop_table("notifications")
    op.drop_table("events")
    op.drop_table("trades")
    op.drop_table("user_settings")
    op.drop_table("broker_credentials")
    op.drop_table("users")
